### PR TITLE
Make Lingua fully aware of the 'Accept-Language' header

### PR DESCRIPTION
**Pull request by homme**
This is a fix for issue #3. It means that Lingua now matches the best
available language tag in the Accept-Language header to a
resource. Previously only the first language tag in the header was
chosen as a locale.

In addition the subtagQvalue option to lingua has been added, with a
value range from 0 to 1 and defaulting to 0.1. If subtagQvalue is
non-zero then the primary subtag in a language tag is also extracted
and matched against a resource. In the language tag 'en-us' the
primary subtag is 'en'.

This change involved:
- creating code to extract and order the language tags and subtags
  based on qvalues.
- enhancing the guru.determines() method to return an ordered list of
  acceptable locales rather than a single locale.
- enhancing guru.ask() to take a list of locales rather than a single
  locale and try to a match a value in the list to a resource.

### CODE REVIEW

**Comment by akoenig** [comment]
Branch "v0.2", I meant.

**Comment by homme** [comment]
Thanks, and I'm glad you're taking the issue on. Feel free to do with the patch as you will - I hope it illustrates the concepts appropriately. I look forward to seeing the result!

**Comment by akoenig** [comment]
Okay, I've integrated your patch and used this opportunity to rearrange the application architecture. Do you have one second for testing the stuff? Would be really cool :)

**Comment by homme** [comment]
Hi André - I've just had a chance to check the v0.2 branch against my app with a few curl commands and it all appears to be working fine:

'Accept-Language: en-gb;q=0.8,en-us;q=0.5,en;q=0.4,fr-be;q=0.3,fr;q=0.2'  -> 'en'
'Accept-Language: en-gb;q=0.8,en-us;q=0.5,fr-be;q=0.3,fr;q=0.2' -> 'fr'
'Accept-Language: en-gb;q=0.8,en-us;q=0.5,fr-be;q=0.3' -> 'en'
'Accept-Language: en-gb;q=0.8,en-us;q=0.5,fr-be;q=0.9' -> 'fr'
'Accept-Language: en-gb,en-us;q=0.5,fr-be;q=0.9' -> 'en'

Looking good!

**Comment by akoenig** [comment]
Hi Homme,

this is great! So in fact the version 0.2.0 is available. Again, thank you very much for your contribution.

Keep up the good work!

**Pull request merged**
